version: "3.9"
services:
  db:
    image: postgres
    container_name: db_food
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=food
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/food/data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    restart: always
  app:
    image: my_food_image
    container_name: my_food
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/food
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 127.0.0.1:8081:8081
    depends_on:
      - db