apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-food
  labels:
    app: my-food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-food
  template:
    metadata:
      labels:
        app: my-food
    spec:
      containers:
        - name: my-food
          image: cyberfuzz/my_food_image
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresdb-secret
                  key: postgres-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgresdb-configmap
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: my-food-service
spec:
  selector:
    app: my-food
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31001